name: Feature request
description: Suggest an improvement.
labels: [enhancement]
assignees: [gouyt13]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to improve?
      description: Describe what you want to do and how the change would help.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Any ideas? (optional)
      description: Share a possible solution or example if you have one.
